### ISSUE TITLE
Can not build scraper

### ISSUE THREAD

**Issue by akrzos** [openshift-scale/perf-analyzer#3]
There is an error when trying to build the scraper at this time

```
$ go build
# github.com/openshift-scale/perf-analyzer/pkg/config
../../pkg/config/config.go:144:74: cannot use c.Metrics (type []metrics.Metrics) as type []metrics.BaseMetrics in field value
```

**Comment by akrzos** [comment]
@hongkailiu Would you be able to help out?

**Comment by hongkailiu** [comment]
Will check today.

**Comment by hongkailiu** [comment]
Did not get the chance today. Will do it next Tuesday (PTO next Monday).
In case of emergency, @sjug knows much more than I do.

**Comment by hongkailiu** [comment]
@akrzos try this?

https://github.com/openshift-scale/perf-analyzer/blob/ed8b9eb85202e578ff33f28fe0b6510c7dcf4b1d/pkg/result/result.go#L16

-->

`Metrics []metrics.Metrics`

**Comment by akrzos** [comment]
@hongkailiu That does seem to fix it, can you provide a pr so we can fix it for our build process?

**Comment by sjug** [comment]
Fixed by https://github.com/openshift-scale/perf-analyzer/pull/4 & https://github.com/openshift-scale/perf-analyzer/pull/5, sorry again @hongkailiu missed your PR.
